version: '3.4'

services:
  app:
    image: app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      # AI_URL: "http://core:5000"
      # SERVICE_URL: "http://service:3000"
      GPT_URL: "http://gpt:5000"
      RASA_URL: "http://rasa:5005"
      QA_URL: "http://qa:5000"
      MONGO_URI: "${MONGO_URI}"
    ports:
      - 80:3000
    depends_on:
      # - core
      # - service
      - gpt
      - rasa
      - qa
  
  # core:
  #   image: core
  #   build:
  #     context: ./core
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 5000:5000
  #   restart: always

  # service:
  #   image: service
  #   build:
  #     context: ./service
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3001:3000

  gpt:
    image: gpt
    build:
      context: ./gpt
      dockerfile: ./Dockerfile
    ports:
      - 3002:5000
    restart: always

  rasa:
    image: rasa-nlu
    ports:
      - 5005:5005
    build:
      context: ./simple-chatbot
      dockerfile: ./Dockerfile
    restart: always

  qa:
    image: qa
    build:
      context: ./qa
      dockerfile: ./Dockerfile
    ports: 
      - 3003:5000
    restart: always
    environment:
      API_KEY: $API_KEY